name: i2dl
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - cffi=1.12.3
  - cudatoolkit=10.0.130
  - cudnn=7.6.0
  - decorator=4.4.0
  - freetype=2.9.1
  - gmp=6.1.2
  - intel-openmp=2019.3
  - ipykernel=5.1.0
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - jinja2=2.10.1
  - jpeg=9b
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - jupyterlab=0.35.6
  - jupyterlab_server=0.2.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.1
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.9.0
  - notebook=5.7.8
  - numpy=1.16.3
  - numpy-base=1.16.3
  - openssl=1.1.1c
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - pexpect=4.7.0
  - pip=19.1.1
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - pycparser=2.19
  - pygments=2.4.0
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytorch=1.1.0
  - readline=7.0
  - setuptools=41.0.1
  - sqlite=3.28.0
  - testpath=0.4.2
  - tk=8.6.8
  - torchvision=0.3.0
  - tornado=6.0.2
  - tqdm=4.32.1
  - traitlets=4.3.2
  - wheel=0.33.4
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - appdirs==1.4.3
    - appnope==0.1.0
    - backports-abc==0.5
    - backports-shutil-get-terminal-size==1.0.0
    - bleach==3.1.0
    - configparser==3.7.4
    - cycler==0.10.0
    - cython==0.29.7
    - defusedxml==0.6.0
    - entrypoints==0.3
    - enum34==1.1.6
    - h5py==2.9.0
    - html5lib==1.0.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.3
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-console==6.0.0
    - kiwisolver==1.1.0
    - matplotlib==3.0.3
    - olefile==0.46
    - packaging==19.0
    - pandas==0.24.2
    - pathlib2==2.3.3
    - pickleshare==0.7.5
    - pillow==6.0.0
    - prometheus-client==0.6.0
    - ptyprocess==0.6.0
    - pyparsing==2.4.0
    - pyrsistent==0.15.2
    - pytz==2019.1
    - pyyaml==5.1
    - pyzmq==18.0.1
    - qtconsole==4.4.4
    - scandir==1.10.0
    - scipy==1.2.1
    - seaborn==0.9.0
    - send2trash==1.5.0
    - simplegeneric==0.8.1
    - singledispatch==3.4.0.3
    - six==1.12.0
    - terminado==0.8.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.4.2
